# Setup
title:                  Software Crafting
tagline:                JVM, GNU/Linux and General tech #by Nicolas Dupouy
url:                    "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:                "" # the subpath of your site, e.g. /blog
locale:                 "en"

# Social
email:                  nicolasdupouy@gmail.com
linkedin_username:      nicolasdupouy
twitter_username:       nicolas_dupouy
github_username:        nicolasdupouy
stackoverflow_username: 2017611/nicolas-dupouy

# Jekyll
highlighter: rouge
markdown: kramdown

plugins:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/ # any user-specific listing goes at the end
